config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  root to: "home#index"

  get 'dashboard' => 'dashboard#index'
  get 'advanced' => 'dashboard#advanced'
  
  resources :plans, only: [:index] do
    member do
      get :checkout
      post :purchase
    end
  end

  resources :search_terms

  resources :locations, only: [] do
    collection do
      get :geocode
    end
  end

  resources :tweets, only: [:index]

  resources :favorites, only: [:create, :index] do
    collection do
      post :unfavorite
    end
  end

  resources :profile, only: [:index] do
    collection do
      put :update
    end
  end

  resources :users, only: [] do
    collection do
      put :toggle_automatic_favoriting
    end
  end

  resources :blacklist_users, only: [:index, :create, :destroy]

  get 'unsubscribe' => 'weekly_report#unsubscribe'

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  authorize_resource class: false
  before_filter :validate_email
  before_filter :find_search_term

  def index
    @favorites = current_user.favorites.where("created_at > ?", 1.day.ago).
      order("created_at DESC")

    @tweets = find_tweets(@selected_search_term)
    @favorited_followers = current_user.favorited_followers
  end

  def advanced
    
  end

  private

  def find_search_term
    @search_terms = current_user.search_terms

    search_term_id = params.delete(:search_term_id)
    @selected_search_term = search_term_id ?
      SearchTerm.find(search_term_id) : nil
  end

  def find_tweets(search_term)
    root = search_term ? search_term : current_user
    root.tweets.where("created_at > ?", 1.day.ago).
      order("created_at DESC")
  end

  def validate_email
    unless current_user.email.present?
      flash[:notice] = "Please enter your email address"
      redirect_to profile_index_path
    end
  end


end

app/views/layouts/dashboard/_navbar.html.erb
<nav class="navbar navbar-fixed-top navbar-theme" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <%= link_to APP_SETTINGS['application_name'], root_path, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if current_user %>
          <li>
            <%= link_to raw("#{fa_icon('twitter')} Tweets"), root_path %>
          </li>
          <li>
            <%= link_to raw("#{fa_icon('star')} Favorites"), favorites_path %>
          </li>
          <li>
            <%= link_to raw("#{fa_icon('search')} Search Terms"), search_terms_path %>
          </li>
          <li>
            <%= link_to raw("#{fa_icon('cogs')} Advanced"), advanced_path %>
          </li>

          <% if current_user.admin %>
            <li>
              <%= link_to raw("#{fa_icon('key')} Admin"), rails_admin_path %>
            </li>
          <% end %>

        <% end %>
        <li>
          <%= link_to raw("#{fa_icon('bar-chart-o')} Plans"), plans_path %>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <li>
            <%= link_to current_user, profile_index_path %>
          </li>
          <li>
            <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
          </li>
        <% else %>
          <li>
            <%= link_to "Sign In", new_user_session_path %>
          </li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->

  </div><!-- /.container-fluid -->
</nav>