config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  root to: "home#index"

  get 'dashboard' => 'dashboard#index'
  get 'advanced' => 'dashboard#advanced'
  
  resources :plans, only: [:index] do
    member do
      get :checkout
      post :purchase
    end
  end

  resources :search_terms

  resources :locations, only: [] do
    collection do
      get :geocode
    end
  end

  resources :tweets, only: [:index]

  resources :favorites, only: [:create, :index] do
    collection do
      post :unfavorite
    end
  end

  resources :profile, only: [:index] do
    collection do
      put :update
    end
  end

  resources :users, only: [] do
    collection do
      put :toggle_automatic_favoriting
    end
  end

  resources :blacklist_users, only: [:index, :create, :destroy]

  get 'unsubscribe' => 'weekly_report#unsubscribe'

end

app/models/search_term.rb
class SearchTerm < ActiveRecord::Base
  attr_accessor :radius

  # keywords, location_id, user_id
  
  belongs_to :location
  belongs_to :user
  has_many :tweets, dependent: :destroy

  validates_presence_of :keywords

  after_create :search!

  def search!
    return true if Rails.env.test?

    processor = TwitterSearchProcessor.new(self, user, TwitterSearcher, TwitterRestClient, Tweet)
    processor.process!
  end

  def to_s
    location ? "#{keywords} in #{location}" : keywords
  end

end

app/controllers/search_terms_controller.rb
class SearchTermsController < ApplicationController
  before_filter :find_search_term, only: [:edit, :update, :destroy]
  before_filter :find_locations, only: [:new, :edit, :update, :create]

  def index
    @search_terms = current_user.search_terms
    @can_add_more_terms = current_user.can_add_more_search_terms?
  end

  def new
    @search_term = SearchTerm.new
  end

  def edit

  end

  def update
    search_term = params[:search_term]
    address = search_term.delete(:location)
    radius = search_term.delete(:radius).to_i

    if address
      location = find_or_build_location(address, radius)
      search_term[:location_id] = location.id if location
    end

    @search_term.update_attributes({
      keywords: search_term[:keywords],
      location_id: search_term[:location_id],
      user: current_user})

    if @search_term.errors.any?
      render :edit
    else
      @search_term.search!
      flash[:notice] = "Search term updated."

      if current_user.search_terms.count > 1
        redirect_to search_terms_path
      else
        redirect_to dashboard_path
      end
    end

  end

  def create
    unless current_user.can_add_more_search_terms?
      flash[:alert] = "You have added your maximum number of search terms for this plan."
      redirect_to search_terms_path and return
    end

    search_term = params[:search_term]
    address = search_term.delete(:location)
    radius = search_term.delete(:radius)

    if address && search_term[:location_id].blank?
      location = find_or_build_location(address, radius)
      search_term[:location_id] = location.id if location
    end

    @search_term = SearchTerm.create(keywords: search_term[:keywords],
      location_id: search_term[:location_id],
      user: current_user)

    if @search_term.errors.any?
      render :new
    else
      flash[:notice] = "Search term added."

      if current_user.search_terms.count > 1
        redirect_to search_terms_path
      else
        redirect_to dashboard_path
      end
    end
  end

  def destroy
    @search_term = SearchTerm.find(params[:id])
    @search_term.destroy

    flash[:notice] = "Search term deleted."
    redirect_to search_terms_path
  end

  private

  def find_or_build_location(address, radius)
    location = Location.where(user_id: current_user.id).find_by_name_and_radius(address, radius)
    return location if location

    searcher = GeoSearcher.new(address, Geocoder)
    begin
      result = searcher.search!
      location = Location.create(
        latitude: result.latitude,
        longitude: result.longitude,
        name: address,
        radius: radius,
        user: current_user)
    rescue GeoSearchNoResultsException => e
    end
    location
  end

  def find_search_term
    @search_term = SearchTerm.find(params[:id])
  end

  def find_locations
    @locations = current_user.locations
  end

end

app/views/search_terms/_form.html.erb
<%= form_for(@search_term, url: url, method: method) do |f| %>
  <% @search_term.errors.full_messages.each do |msg| %>
    <p class='text-danger'><%= msg %></p>
  <% end %>

  <div class='row'>
    <div class='form-group col-md-6'>
      <%= f.label :keywords %>
      <%= f.text_field :keywords, class: 'form-control',
         placeholder: 'coffee' %>
      <p class="help-block">
        - Only one keyword per search term<br/>
        - Pick a keyword related to your business.<br/>
        - For example, a coffee shop might favorite users that say they are 'sleepy'.
      </p>
    </div>
  </div>

  <div class='row'>
    <div class='row col-md-6'>
      <div class='form-group col-md-12'>
        <%= f.label :location, "Address (optional)" %>
        <%= f.text_field :location, class: 'form-control',
          placeholder: '1600 Pennsylvania Ave NW, Washington, DC 20500' %>
        <%= f.hidden_field :location_id %>
      </div>

      <p class='found-location col-md-12 hidden'>
        <strong>Latitude: </strong>
        <span id='latitude'></span>
        <strong>Longitude: </strong>
        <span id='longitude'></span>
      </p>

      <div class='col-md-12'>
        <% location = @search_term.location %>

        <%= f.label :radius, "Search Radius (km, optional)" %>
        <%= f.text_field :radius, class: 'form-control', placeholder: 10,
          value: location ? location.radius : nil %>
      </div>
    </div>

    <div class='col-md-6'>
      <% if @locations.any? %>
        <h5>Your Locations</h5>
        <ul class='list-unstyled'>
          <% @locations.each do |location| %>
            <li>
              <%= link_to "#{location} (#{location.radius}#{location.radius_unit})", "#", class: 'past-location',
                "data-location-id" => location.id,
                "data-location-name" => location.name,
                "data-location-radius" => location.radius %>
            </li>
          <% end %>
        </ul>
      <% end %>
    </div>
  </div>

  <hr/>

  <div class='form-group'>
    <%= f.submit message, class: 'btn btn-success' %>
  </div>
<% end %>

app/views/search_terms/edit.html.erb
<h1>Edit Search Term</h1>

<%= render partial: "form", locals:
  { url: search_term_path(@search_term),
    method: :put,
    message: "Edit Search Term"}
%>

app/views/search_terms/index.html.erb
<h1>Search Terms</h1>

<% if @can_add_more_terms %>
  <div class='row'>
    <div class='col-md-1'>
      <%= link_to "Add", new_search_term_path, class: 'btn btn-primary' %>
    </div>
  </div>
<% else %>
  <div class='alert alert-warning'>
    <h4 class='text-center'>You have run out of search terms for this plan!</h4>
    <p class='text-center'><%= link_to "Upgrade your plan to add additional search terms", plans_path %></p>
  </div>
<% end %>

<hr/>

<% if @search_terms.any? %>
  <table class='table table-bordered'>
    <tr>
      <th>Keywords</th>
      <th>Location</th>
      <th>Tweets in Last 30 Days</th>
      <th></th>
    </tr>
    <% @search_terms.each do |search_term| %>
      <tr>
        <td><%= search_term.keywords %></td>
        <td><%= search_term.location %></td>
        <td><%= search_term.tweets.since(30.days.ago).count %></td>
        <td>
            <%= link_to "Edit", edit_search_term_path(search_term) %>
            |
            <%= link_to "Delete", search_term_path(search_term),
                method: :delete,
                data: {confirm: "Are you sure you would like to delete this search term? All tweets will be deleted."}
            %>
        </td>
      </tr>
    <% end %>
  </table>

<% else %>
  <div class='well'>
    <h3 class='text-center'><%= link_to "Add your first search term to get started.", new_search_term_path %></h3>
  </div>
<% end %>

app/views/search_terms/new.html.erb
<h1>New Search Term</h1>

<%= render partial: "form", locals:
  { url: search_terms_path,
    method: :post,
    message: "Add Search Term"} 
%>