config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  root to: "home#index"

  get 'dashboard' => 'dashboard#index'
  get 'advanced' => 'dashboard#advanced'
  
  resources :plans, only: [:index] do
    member do
      get :checkout
      post :purchase
    end
  end

  resources :search_terms

  resources :locations, only: [] do
    collection do
      get :geocode
    end
  end

  resources :tweets, only: [:index]

  resources :favorites, only: [:create, :index] do
    collection do
      post :unfavorite
    end
  end

  resources :profile, only: [:index] do
    collection do
      put :update
    end
  end

  resources :users, only: [] do
    collection do
      put :toggle_automatic_favoriting
    end
  end

  resources :blacklist_users, only: [:index, :create, :destroy]

  get 'unsubscribe' => 'weekly_report#unsubscribe'

end

app/models/plan.rb
class Plan < ActiveRecord::Base
  # name, description, amount, stripe_plan_id
  # public, automatic_favoriting_enabled, max_search_terms, max_favorites_per_day
  has_many :user_plans

  def free?
    amount == 0
  end

end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  before_filter :find_plan_or_fail, only: [:checkout, :purchase]

  def index
    @current_plan = current_user.plan if current_user
    @plans = [DefaultPlan.new] + Plan.where(public: true)
  end

  def checkout

  end

  def purchase
    card_token = params[:stripeToken]

    purchaser = StripePlanPurchaser.new(
      card_token, @plan.stripe_plan_id, current_user)

    if purchaser.purchase_plan!
      user_plan = UserPlan.create(
        plan: @plan,
        user: current_user,
        stripe_subscription_id: purchaser.subscription_id,
        stripe_customer_id: purchaser.customer_id
      )

      flash[:alert] = nil
      flash[:notice] = "Your plan was purchased successfully."
      redirect_to dashboard_path
    else
      flash[:alert] = "An error occurred purchasing this plan: #{purchaser.error}"
      render :checkout
    end
  end

  private

  def find_plan_or_fail
    @plan = Plan.find_by_id(params[:id])
    redirect_to dashboard_path unless @plan
  end

end

app/views/plans/checkout.html.erb
<%= content_for :javascript do %>
  <script type="text/javascript" src="https://js.stripe.com/v2/"></script>
<% end %>

<h1>Purchase Plan</h1>

<div class='row'>
  <div class='col-md-6'>
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">
          <%= @plan.name %> - <%= number_to_currency(@plan.amount) %>/mo
        </h3>
      </div>
      <div class="panel-body">
        <%= form_tag(purchase_plan_path(@plan), method: :post, id: 'payment-form') do %>
          <div class="payment-errors"></div>

          <div class="form-group">
            <%= label_tag "paymentCardNumber", "Card Number" %>
            <%= text_field_tag :number, nil, class: 'form-control',
              id: 'paymentCardNumber', "data-stripe" => "number", size: 20 %>
          </div>

          <div class='row'>
            <div class="form-group col-md-4">
              <%= label_tag "paymentCVC", "CVC" %>
              <%= text_field_tag :cvc, nil, class: 'form-control',
                id: 'paymentCVC', "data-stripe" => "cvc", size: 4 %>
            </div>

            <div class="form-group col-md-8">
              <%= label_tag "paymentMonth", "Expiration (MM/YYYY)" %>
              <div class='row'>
                <div class='col-md-6'>
                  <%= text_field_tag :paymentMonth, nil, class: 'form-control',
                    id: 'paymentMonth', "data-stripe" => "exp-month", size: 2,
                    placeholder: '01' %>
                </div>
                <div class='col-md-6'>
                  <%= text_field_tag :paymentYear, nil, class: 'form-control',
                    id: 'paymentYear', "data-stripe" => "exp-year", size: 4,
                    placeholder: '2019' %>
                </div>
              </div>
            </div>
          </div>

          <%= submit_tag "Purchase", class: 'btn btn-success' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/plans/index.html.erb
<h1>Plans</h1>

<div class='row'>
  <table class='col-md-12 plans-table'>
    <% @plans.each do |plan| %>
      <td width="33%" class="row plan <%= plan == @current_plan ? 'plan-current' : nil %>">
        <h2><%= plan.name %></h2>
        <div class='description'><%= plan.description %></div>
        <div class='price'>
          <% if plan.free? %>
            Free
          <% else %>
            <%= number_to_currency(plan.amount) %>/mo
          <% end %>
        </div>
        <div class='purchase'>
          <% unless plan.free? || @current_plan == plan %>
          <% purchase_link = current_user ? checkout_plan_path(plan) : user_omniauth_authorize_path(:twitter) %>
          <%= link_to "Purchase", purchase_link,
              class: 'btn btn-success btn-purchase' %>
          <% end %>
        </div>
      </td>
    <% end %>
  </table>
</div>